"""
Django settings for mysite project.

Generated by 'django-admin startproject' using Django 5.2.7.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-+-jt+7^!^)el55u6u25wfe+$00^ch@siowltw2^9^$3+r6u0-n'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

# ALLOWED_HOSTS = []
ALLOWED_HOSTS = ['crm.erpnext.ai', '147.79.67.128', 'localhost', '127.0.0.1']


CSRF_TRUSTED_ORIGINS = [
    'https://crm.erpnext.ai',
    'https://www.crm.erpnext.ai',
]


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
     'myapp'
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'mysite.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'mysite.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.sqlite3',
#         'NAME': BASE_DIR / 'db.sqlite3',
#     }
# }


# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.mysql',
#         'NAME': 'test',   # e.g. 'crm_db'
#         'USER': 'root',                 # your MySQL username
#         'PASSWORD': '1234',    # your MySQL password
#         'HOST': 'localhost',            # or '127.0.0.1'
#         'PORT': '3306',                 # default MySQL port
#         'OPTIONS': {
#             'init_command': "SET sql_mode='STRICT_TRANS_TABLES'",
#         },
#     }
# }


DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'crmdjango',           # Default Schema / Database Name
        'USER': 'crmdjango',           # MySQL Username
        'PASSWORD': 'admin',           # MySQL Password
        'HOST': '103.214.132.20',      # Remote Host
        'PORT': '3306',                # MySQL Port
        'OPTIONS': {
            'init_command': "SET sql_mode='STRICT_TRANS_TABLES'",
        },
    }
}




# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

# STATIC_URL = 'static/'
STATIC_URL = '/static/'
STATICFILES_DIRS = [BASE_DIR / "static"] 

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


# EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
# EMAIL_HOST = 'bv-b29.yuvanetworks.in'       # SMTP server
# EMAIL_PORT = 587                             # SMTP port
# EMAIL_USE_TLS = False   # STARTTLS
# EMAIL_HOST_USER = 'sales@psdigitise.com'  # Your SMTP username
# EMAIL_HOST_PASSWORD = 'O0TLL0u3iQ'           # Your SMTP password
# DEFAULT_FROM_EMAIL = 'sales@psdigitise.com'


# Email Configuration
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'bv-b29.yuvanetworks.in'       # SMTP server
EMAIL_PORT = 587                            # SMTP port
EMAIL_USE_TLS = False                        # STARTTLS (enabled)
EMAIL_HOST_USER = 'info@erpnext.ai'         # Your SMTP username
EMAIL_HOST_PASSWORD = 'IEWMrFKFWl'          # Your SMTP password
DEFAULT_FROM_EMAIL = 'info@erpnext.ai'


# settings.py
# RAZORPAY_KEY_ID = "rzp_test_RQ8oEOotOQ7P2E"
# RAZORPAY_KEY_SECRET = "ne9t5RopGsCszrH5i8MXT5fY"

# Razorpay Live Keys
RAZORPAY_KEY_ID = 'rzp_live_RbHLiSn5xiGADx'
RAZORPAY_KEY_SECRET = 'ttN1tdudQjx4QczEcJeKjYkx'



